apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sleep-then-test-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: sleep-then-test-app
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://github.com/danxmoran/argo-cd-reproducers
    path: sleep-then-test
    targetRevision: HEAD
    helm:
      values: >
        input: original
