apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-input-cron
  labels:
    app.kubernetes.io/name: test-input-cron
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: test-input-cron
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: test-input-cron
        spec:
          restartPolicy: Never
          containers:
            - name: tester
              image: alpine:3.23.0
              command: [test, '{{ .Values.input }}', =, original]
